// This file contains the car parts data from the provided text file

export const carParts = {
  front: [
    "Capot",
    "Capot bisagras",
    "Capot cierre",
    "Capot molduras",
    "Cubrepledras",
    "Defensa",
    "Faro derecho",
    "Faro derecho aro",
    "Faro izquierdo",
    "Faro izquierdo aro",
    "Farito derecho",
    "Farito izquierdo",
    "Guardabarro der",
    "Guardabarro der. Guardapolvo",
    "Guardabarro der. Moldura",
    "Guardabarro izq",
    "Guardabarro izq. Guardapolvo",
    "Guardabarro izq. Moldura",
    "Panel frente: Insig",
    "Panel frente: moldura",
    "Panel frente: sup/inf",
    "Paragolpes",
    "Parabrisas cristal / mold / burlete",
    "Parabrisas parantes",
    "Rejilla radiador",
    "Rejilla radiador Insig",
    "Rejilla radiador marco",
    "Soportes",
    "Torpedo lado der",
    "Torpedo lado izq",
    "Uña",
  ],
  rear: [
    "Cubrepledras",
    "Defensa",
    "Farito centro",
    "Farito derecho",
    "Farito izquierdo",
    "Guardabarro der",
    "Guardabarro der. Guardapolvo",
    "Guardabarro der. Moldura",
    "Guardabarro izq",
    "Guardabarro izq. Guardapolvo",
    "Guardabarro izq. Moldura",
    "Luneta cristal / mold / burlete",
    "Luneta marco",
    "Panel",
    "Paragolpes",
    "Piso baúl",
    "Soportes",
    "Tapa baúl / motor / burlete",
    "Techo",
    "Uña",
  ],
  interior: [
    "Alfombras",
    "Bandeja",
    "Bocina",
    "Brazo y cepillo limp. Parabrisas",
    "Espejo retrovisor",
    "Estructura de asiento",
    "Guías asiento der",
    "Guías asiento tras",
    "Instalación eléctrica",
    "Instrumental",
    "Marcos",
    "Motor limpia parabrisas",
    "Piso de baúl",
    "Piso lado der",
    "Piso lado izq",
    "Radio / antena",
    "Tablero de Instrum",
    "Tapizado asientos del",
    "Tapizado asientos tras",
    "Tapizado puerta del. Der",
    "Tapizado puerta del. Izq",
    "Tapizado puerta tras. Der",
    "Tapizado puerta tras. Izq",
    "Tapizado tablero Inf./sup",
    "Tapizados techo",
  ],
  right: [
    "Cristales de panel",
    "Gotera",
    "Gotera moldura",
    "Panel",
    "Parante centro",
    "Parante delantero",
    "Parante trasero",
    "Puerta delantera",
    "Puerta delantera bisagra",
    "Puerta delantera manija",
    "Puerta delantera marco",
    "Puerta delantera moldura",
    "Puerta trasera",
    "Puerta trasera bisagras",
    "Puerta trasera manija",
    "Puerta trasera marco",
    "Puerta trasera moldura",
  ],
  left: [
    "Cristales de panel",
    "Gotera",
    "Gotera moldura",
    "Panel",
    "Parante centro",
    "Parante delantero",
    "Parante trasero",
    "Puerta delantera",
    "Puerta delantera bisagra",
    "Puerta delantera manija",
    "Puerta delantera marco",
    "Puerta delantera moldura",
    "Puerta trasera",
    "Puerta trasera bisagras",
    "Puerta trasera manija",
    "Puerta trasera marco",
    "Puerta trasera moldura",
  ],
  engine: [
    "Batería",
    "Batería cajón",
    "Block",
    "Bobina",
    "Bomba de agua",
    "Bomba de nafta",
    "Caño de escape",
    "Caños de goma",
    "Carburador",
    "Dinamo",
    "Distribuidor",
    "Instalación eléctrica",
    "Motor de arranque",
    "Radiador / pañol",
    "Soportes",
    "Tanque de nafta",
    "Ventilador",
  ],
  chassis: [
    "Aro del volante",
    "Barras",
    "Brazo Pitman",
    "Caja de dirección",
    "Caja de velocidad",
    "Carcaza de tubo",
    "Cardan",
    "Crucetas",
    "Diferencial",
    "Embrague",
    "Extremo izq. / der.",
    "Falso chasis",
    "Larguero derecho",
    "Larguero izquierdo",
    "Mangas del diferencial",
    "Palieres",
    "Piñón / corona",
    "Rulemanes",
    "Sector y sinfín",
    "Travesaño delantero",
    "Travesaño trasero",
    "Tubo",
    "Varillaje",
    "Volante",
  ],
}
